-- fill the ingredients table without relation to snacks first
INSERT INTO ingredients (id, name) VALUES (1, "7-Up");
INSERT INTO ingredients (id, name) VALUES (2, "Absinthe");
INSERT INTO ingredients (id, name) VALUES (3, "Absolut Citron");
INSERT INTO ingredients (id, name) VALUES (4, "Absolut Kurant");
INSERT INTO ingredients (id, name) VALUES (5, "Absolut Peppar");
INSERT INTO ingredients (id, name) VALUES (6, "Absolut Vodka");
INSERT INTO ingredients (id, name) VALUES (7, "Advocaat");
INSERT INTO ingredients (id, name) VALUES (8, "Agave Syrup");
INSERT INTO ingredients (id, name) VALUES (9, "Ale");
INSERT INTO ingredients (id, name) VALUES (10, "Allspice");
INSERT INTO ingredients (id, name) VALUES (11, "Almond");
INSERT INTO ingredients (id, name) VALUES (12, "Almond Flavoring");
INSERT INTO ingredients (id, name) VALUES (13, "Amaretto");
INSERT INTO ingredients (id, name) VALUES (14, "Amaro Montenegro");
INSERT INTO ingredients (id, name) VALUES (15, "Añejo Rum");
INSERT INTO ingredients (id, name) VALUES (16, "Angelica Root");
INSERT INTO ingredients (id, name) VALUES (17, "Angostura Bitters");
INSERT INTO ingredients (id, name) VALUES (18, "Anis");
INSERT INTO ingredients (id, name) VALUES (19, "Anise");
INSERT INTO ingredients (id, name) VALUES (20, "Anisette");
INSERT INTO ingredients (id, name) VALUES (21, "Aperol");
INSERT INTO ingredients (id, name) VALUES (22, "Apple");
INSERT INTO ingredients (id, name) VALUES (23, "Apple Brandy");
INSERT INTO ingredients (id, name) VALUES (24, "Apple Cider");
INSERT INTO ingredients (id, name) VALUES (25, "Apple Juice");
INSERT INTO ingredients (id, name) VALUES (26, "Apple Schnapps");
INSERT INTO ingredients (id, name) VALUES (27, "Applejack");
INSERT INTO ingredients (id, name) VALUES (28, "Apricot");
INSERT INTO ingredients (id, name) VALUES (29, "Apricot Brandy");
INSERT INTO ingredients (id, name) VALUES (30, "Apricot Nectar");
INSERT INTO ingredients (id, name) VALUES (31, "Aquavit");
INSERT INTO ingredients (id, name) VALUES (32, "Bacardi");
INSERT INTO ingredients (id, name) VALUES (33, "Bacardi Limon");
INSERT INTO ingredients (id, name) VALUES (34, "Baileys Irish Cream");
INSERT INTO ingredients (id, name) VALUES (35, "Banana");
INSERT INTO ingredients (id, name) VALUES (36, "Banana Liqueur");
INSERT INTO ingredients (id, name) VALUES (37, "Basil");
INSERT INTO ingredients (id, name) VALUES (38, "Beer");
INSERT INTO ingredients (id, name) VALUES (39, "Benedictine");
INSERT INTO ingredients (id, name) VALUES (40, "Bitter Lemon");
INSERT INTO ingredients (id, name) VALUES (41, "Bitters");
INSERT INTO ingredients (id, name) VALUES (42, "Black Sambuca");
INSERT INTO ingredients (id, name) VALUES (43, "Blackberries");
INSERT INTO ingredients (id, name) VALUES (44, "Blackberry Brandy");
INSERT INTO ingredients (id, name) VALUES (45, "Blackcurrant Cordial");
INSERT INTO ingredients (id, name) VALUES (46, "Blackcurrant Squash");
INSERT INTO ingredients (id, name) VALUES (47, "Blackstrap Rum");
INSERT INTO ingredients (id, name) VALUES (48, "Blended Scotch");
INSERT INTO ingredients (id, name) VALUES (49, "Blended Whiskey");
INSERT INTO ingredients (id, name) VALUES (50, "Blood Orange");
INSERT INTO ingredients (id, name) VALUES (51, "Blue Curacao");
INSERT INTO ingredients (id, name) VALUES (52, "Blueberries");
INSERT INTO ingredients (id, name) VALUES (53, "Bourbon");
INSERT INTO ingredients (id, name) VALUES (54, "Brandy");
INSERT INTO ingredients (id, name) VALUES (55, "Brown Sugar");
INSERT INTO ingredients (id, name) VALUES (56, "Butterscotch Schnapps");
INSERT INTO ingredients (id, name) VALUES (57, "Cachaca");
INSERT INTO ingredients (id, name) VALUES (58, "Campari");
INSERT INTO ingredients (id, name) VALUES (59, "Candy");
INSERT INTO ingredients (id, name) VALUES (60, "Caramel Coloring");
INSERT INTO ingredients (id, name) VALUES (61, "Caramel Sauce");
INSERT INTO ingredients (id, name) VALUES (62, "Carbonated Water");
INSERT INTO ingredients (id, name) VALUES (63, "Celery Salt");
INSERT INTO ingredients (id, name) VALUES (64, "Chambord Raspberry Liqueur");
INSERT INTO ingredients (id, name) VALUES (65, "Champagne");
INSERT INTO ingredients (id, name) VALUES (66, "Cherry");
INSERT INTO ingredients (id, name) VALUES (67, "Cherry Brandy");
INSERT INTO ingredients (id, name) VALUES (68, "Cherry Grenadine");
INSERT INTO ingredients (id, name) VALUES (69, "Cherry Heering");
INSERT INTO ingredients (id, name) VALUES (70, "Cherry Juice");
INSERT INTO ingredients (id, name) VALUES (71, "Cherry Liqueur");
INSERT INTO ingredients (id, name) VALUES (72, "Chocolate Ice-Cream");
INSERT INTO ingredients (id, name) VALUES (73, "Chocolate Liqueur");
INSERT INTO ingredients (id, name) VALUES (74, "Chocolate Sauce");
INSERT INTO ingredients (id, name) VALUES (75, "Chocolate Syrup");
INSERT INTO ingredients (id, name) VALUES (76, "Cider");
INSERT INTO ingredients (id, name) VALUES (77, "Cinnamon");
INSERT INTO ingredients (id, name) VALUES (78, "Cloves");
INSERT INTO ingredients (id, name) VALUES (79, "Club Soda");
INSERT INTO ingredients (id, name) VALUES (80, "Coca-Cola");
INSERT INTO ingredients (id, name) VALUES (81, "Cocoa Powder");
INSERT INTO ingredients (id, name) VALUES (82, "Coconut Liqueur");
INSERT INTO ingredients (id, name) VALUES (83, "Coconut Rum");
INSERT INTO ingredients (id, name) VALUES (84, "Coconut Syrup");
INSERT INTO ingredients (id, name) VALUES (85, "Coffee");
INSERT INTO ingredients (id, name) VALUES (86, "Coffee Liqueur");
INSERT INTO ingredients (id, name) VALUES (87, "Cognac");
INSERT INTO ingredients (id, name) VALUES (88, "Cointreau");
INSERT INTO ingredients (id, name) VALUES (89, "Condensed Milk");
INSERT INTO ingredients (id, name) VALUES (90, "Coriander");
INSERT INTO ingredients (id, name) VALUES (91, "Corn Syrup");
INSERT INTO ingredients (id, name) VALUES (92, "Corona");
INSERT INTO ingredients (id, name) VALUES (93, "Cranberries");
INSERT INTO ingredients (id, name) VALUES (94, "Cranberry Juice");
INSERT INTO ingredients (id, name) VALUES (95, "Cream");
INSERT INTO ingredients (id, name) VALUES (96, "Cream Of Coconut");
INSERT INTO ingredients (id, name) VALUES (97, "Creme De Banane");
INSERT INTO ingredients (id, name) VALUES (98, "Creme De Cacao");
INSERT INTO ingredients (id, name) VALUES (99, "Creme De Cassis");
INSERT INTO ingredients (id, name) VALUES (100, "Creme De Mure");
INSERT INTO ingredients (id, name) VALUES (101, "Crown Royal");
INSERT INTO ingredients (id, name) VALUES (102, "Cucumber");
INSERT INTO ingredients (id, name) VALUES (103, "Curacao");
INSERT INTO ingredients (id, name) VALUES (104, "Dark Creme De Cacao");
INSERT INTO ingredients (id, name) VALUES (105, "Dark Rum");
INSERT INTO ingredients (id, name) VALUES (106, "Demerara Sugar");
INSERT INTO ingredients (id, name) VALUES (107, "Dry Vermouth");
INSERT INTO ingredients (id, name) VALUES (108, "Dubonnet Rouge");
INSERT INTO ingredients (id, name) VALUES (109, "Egg");
INSERT INTO ingredients (id, name) VALUES (110, "Egg White");
INSERT INTO ingredients (id, name) VALUES (111, "Egg Yolk");
INSERT INTO ingredients (id, name) VALUES (112, "Elderflower Cordial");
INSERT INTO ingredients (id, name) VALUES (113, "Erin Cream");
INSERT INTO ingredients (id, name) VALUES (114, "Espresso");
INSERT INTO ingredients (id, name) VALUES (115, "Everclear");
INSERT INTO ingredients (id, name) VALUES (116, "Falernum");
INSERT INTO ingredients (id, name) VALUES (117, "Fennel Seeds");
INSERT INTO ingredients (id, name) VALUES (118, "Figs");
INSERT INTO ingredients (id, name) VALUES (119, "Firewater");
INSERT INTO ingredients (id, name) VALUES (120, "Food Coloring");
INSERT INTO ingredients (id, name) VALUES (121, "Frangelico");
INSERT INTO ingredients (id, name) VALUES (122, "Fresca");
INSERT INTO ingredients (id, name) VALUES (123, "Fresh Lemon Juice");
INSERT INTO ingredients (id, name) VALUES (124, "Fresh Lime Juice");
INSERT INTO ingredients (id, name) VALUES (125, "Fruit");
INSERT INTO ingredients (id, name) VALUES (126, "Fruit Juice");
INSERT INTO ingredients (id, name) VALUES (127, "Fruit Punch");
INSERT INTO ingredients (id, name) VALUES (128, "Galliano");
INSERT INTO ingredients (id, name) VALUES (129, "Gin");
INSERT INTO ingredients (id, name) VALUES (130, "Ginger");
INSERT INTO ingredients (id, name) VALUES (131, "Ginger Ale");
INSERT INTO ingredients (id, name) VALUES (132, "Ginger Beer");
INSERT INTO ingredients (id, name) VALUES (133, "Ginger Syrup");
INSERT INTO ingredients (id, name) VALUES (134, "Glycerine");
INSERT INTO ingredients (id, name) VALUES (135, "Godiva Liqueur");
INSERT INTO ingredients (id, name) VALUES (136, "Gold Rum");
INSERT INTO ingredients (id, name) VALUES (137, "Gold Tequila");
INSERT INTO ingredients (id, name) VALUES (138, "Goldschlager");
INSERT INTO ingredients (id, name) VALUES (139, "Grain Alcohol");
INSERT INTO ingredients (id, name) VALUES (140, "Grand Marnier");
INSERT INTO ingredients (id, name) VALUES (141, "Grape Juice");
INSERT INTO ingredients (id, name) VALUES (142, "Grape Soda");
INSERT INTO ingredients (id, name) VALUES (143, "Grapefruit Juice");
INSERT INTO ingredients (id, name) VALUES (144, "Green Chartreuse");
INSERT INTO ingredients (id, name) VALUES (145, "Green Creme De Menthe");
INSERT INTO ingredients (id, name) VALUES (146, "Grenadine");
INSERT INTO ingredients (id, name) VALUES (147, "Guinness Stout");
INSERT INTO ingredients (id, name) VALUES (148, "Half-And-Half");
INSERT INTO ingredients (id, name) VALUES (149, "Heavy Cream");
INSERT INTO ingredients (id, name) VALUES (150, "Honey");
INSERT INTO ingredients (id, name) VALUES (151, "Honey Syrup");
INSERT INTO ingredients (id, name) VALUES (152, "Hot Chocolate");
INSERT INTO ingredients (id, name) VALUES (153, "Hot Damn");
INSERT INTO ingredients (id, name) VALUES (154, "Hot Sauce");
INSERT INTO ingredients (id, name) VALUES (155, "Hpnotiq");
INSERT INTO ingredients (id, name) VALUES (156, "Ice");
INSERT INTO ingredients (id, name) VALUES (157, "Iced Tea");
INSERT INTO ingredients (id, name) VALUES (158, "Irish Cream");
INSERT INTO ingredients (id, name) VALUES (159, "Irish Whiskey");
INSERT INTO ingredients (id, name) VALUES (160, "Islay Single Malt Scotch");
INSERT INTO ingredients (id, name) VALUES (161, "Jack Daniels");
INSERT INTO ingredients (id, name) VALUES (162, "Jägermeister");
INSERT INTO ingredients (id, name) VALUES (163, "Jello");
INSERT INTO ingredients (id, name) VALUES (164, "Jim Beam");
INSERT INTO ingredients (id, name) VALUES (165, "Johnnie Walker");
INSERT INTO ingredients (id, name) VALUES (166, "Kahlua");
INSERT INTO ingredients (id, name) VALUES (167, "Kirschwasser");
INSERT INTO ingredients (id, name) VALUES (168, "Kiwi");
INSERT INTO ingredients (id, name) VALUES (169, "Kiwi Liqueur");
INSERT INTO ingredients (id, name) VALUES (170, "Kool-Aid");
INSERT INTO ingredients (id, name) VALUES (171, "Kummel");
INSERT INTO ingredients (id, name) VALUES (172, "Lager");
INSERT INTO ingredients (id, name) VALUES (173, "Lavender");
INSERT INTO ingredients (id, name) VALUES (174, "Lemon");
INSERT INTO ingredients (id, name) VALUES (175, "Lemon Juice");
INSERT INTO ingredients (id, name) VALUES (176, "Lemon Peel");
INSERT INTO ingredients (id, name) VALUES (177, "Lemon Vodka");
INSERT INTO ingredients (id, name) VALUES (178, "Lemon-Lime Soda");
INSERT INTO ingredients (id, name) VALUES (179, "Lemonade");
INSERT INTO ingredients (id, name) VALUES (180, "Licorice Root");
INSERT INTO ingredients (id, name) VALUES (181, "Light Cream");
INSERT INTO ingredients (id, name) VALUES (182, "Light Rum");
INSERT INTO ingredients (id, name) VALUES (183, "Lillet");
INSERT INTO ingredients (id, name) VALUES (184, "Lillet Blanc");
INSERT INTO ingredients (id, name) VALUES (185, "Lime");
INSERT INTO ingredients (id, name) VALUES (186, "Lime Juice");
INSERT INTO ingredients (id, name) VALUES (187, "Lime Juice Cordial");
INSERT INTO ingredients (id, name) VALUES (188, "Limeade");
INSERT INTO ingredients (id, name) VALUES (189, "Malibu Rum");
INSERT INTO ingredients (id, name) VALUES (190, "Mango");
INSERT INTO ingredients (id, name) VALUES (191, "Maple Syrup");
INSERT INTO ingredients (id, name) VALUES (192, "Maraschino Cherry");
INSERT INTO ingredients (id, name) VALUES (193, "Maraschino Liqueur");
INSERT INTO ingredients (id, name) VALUES (194, "Marjoram Leaves");
INSERT INTO ingredients (id, name) VALUES (195, "Maui");
INSERT INTO ingredients (id, name) VALUES (196, "Melon Liqueur");
INSERT INTO ingredients (id, name) VALUES (197, "Mezcal");
INSERT INTO ingredients (id, name) VALUES (198, "Midori Melon Liqueur");
INSERT INTO ingredients (id, name) VALUES (199, "Milk");
INSERT INTO ingredients (id, name) VALUES (200, "Mini-Snickers Bars");
INSERT INTO ingredients (id, name) VALUES (201, "Mint");
INSERT INTO ingredients (id, name) VALUES (202, "Mountain Dew");
INSERT INTO ingredients (id, name) VALUES (203, "Nutmeg");
INSERT INTO ingredients (id, name) VALUES (204, "Olive");
INSERT INTO ingredients (id, name) VALUES (205, "Olive Brine");
INSERT INTO ingredients (id, name) VALUES (206, "Orange");
INSERT INTO ingredients (id, name) VALUES (207, "Orange Bitters");
INSERT INTO ingredients (id, name) VALUES (208, "Orange Curacao");
INSERT INTO ingredients (id, name) VALUES (209, "Orange Juice");
INSERT INTO ingredients (id, name) VALUES (210, "Orange Peel");
INSERT INTO ingredients (id, name) VALUES (211, "Orange Spiral");
INSERT INTO ingredients (id, name) VALUES (212, "Oreo Cookie");
INSERT INTO ingredients (id, name) VALUES (213, "Orgeat Syrup");
INSERT INTO ingredients (id, name) VALUES (214, "Ouzo");
INSERT INTO ingredients (id, name) VALUES (215, "Passion Fruit Juice");
INSERT INTO ingredients (id, name) VALUES (216, "Passion Fruit Syrup");
INSERT INTO ingredients (id, name) VALUES (217, "Passoa");
INSERT INTO ingredients (id, name) VALUES (218, "Peach Bitters");
INSERT INTO ingredients (id, name) VALUES (219, "Peach Brandy");
INSERT INTO ingredients (id, name) VALUES (220, "Peach Nectar");
INSERT INTO ingredients (id, name) VALUES (221, "Peach Schnapps");
INSERT INTO ingredients (id, name) VALUES (222, "Peach Vodka");
INSERT INTO ingredients (id, name) VALUES (223, "Peachtree Schnapps");
INSERT INTO ingredients (id, name) VALUES (224, "Pepper");
INSERT INTO ingredients (id, name) VALUES (225, "Peppermint Extract");
INSERT INTO ingredients (id, name) VALUES (226, "Peppermint Schnapps");
INSERT INTO ingredients (id, name) VALUES (227, "Pepsi Cola");
INSERT INTO ingredients (id, name) VALUES (228, "Pineapple");
INSERT INTO ingredients (id, name) VALUES (229, "Pineapple Juice");
INSERT INTO ingredients (id, name) VALUES (230, "Pineapple Syrup");
INSERT INTO ingredients (id, name) VALUES (231, "Pink Lemonade");
INSERT INTO ingredients (id, name) VALUES (232, "Pisang Ambon");
INSERT INTO ingredients (id, name) VALUES (233, "Pisco");
INSERT INTO ingredients (id, name) VALUES (234, "Pomegranate Juice");
INSERT INTO ingredients (id, name) VALUES (235, "Port");
INSERT INTO ingredients (id, name) VALUES (236, "Powdered Sugar");
INSERT INTO ingredients (id, name) VALUES (237, "Prosecco");
INSERT INTO ingredients (id, name) VALUES (238, "Raisins");
INSERT INTO ingredients (id, name) VALUES (239, "Raspberry Liqueur");
INSERT INTO ingredients (id, name) VALUES (240, "Raspberry Syrup");
INSERT INTO ingredients (id, name) VALUES (241, "Raspberry Vodka");
INSERT INTO ingredients (id, name) VALUES (242, "Red Chili Flakes");
INSERT INTO ingredients (id, name) VALUES (243, "Red Wine");
INSERT INTO ingredients (id, name) VALUES (244, "Ricard");
INSERT INTO ingredients (id, name) VALUES (245, "Root Beer");
INSERT INTO ingredients (id, name) VALUES (246, "Rose");
INSERT INTO ingredients (id, name) VALUES (247, "Rosemary");
INSERT INTO ingredients (id, name) VALUES (248, "Rosemary Syrup");
INSERT INTO ingredients (id, name) VALUES (249, "Roses Sweetened Lime Juice");
INSERT INTO ingredients (id, name) VALUES (250, "Rosso Vermouth");
INSERT INTO ingredients (id, name) VALUES (251, "Ruby Port");
INSERT INTO ingredients (id, name) VALUES (252, "Rum");
INSERT INTO ingredients (id, name) VALUES (253, "Rumple Minze");
INSERT INTO ingredients (id, name) VALUES (254, "Rye Whiskey");
INSERT INTO ingredients (id, name) VALUES (255, "Salt");
INSERT INTO ingredients (id, name) VALUES (256, "Salted Chocolate");
INSERT INTO ingredients (id, name) VALUES (257, "Sambuca");
INSERT INTO ingredients (id, name) VALUES (258, "Schweppes Russchian");
INSERT INTO ingredients (id, name) VALUES (259, "Scotch");
INSERT INTO ingredients (id, name) VALUES (260, "Sherry");
INSERT INTO ingredients (id, name) VALUES (261, "Sirup Of Roses");
INSERT INTO ingredients (id, name) VALUES (262, "Sloe Gin");
INSERT INTO ingredients (id, name) VALUES (263, "Soda Water");
INSERT INTO ingredients (id, name) VALUES (264, "Sour Mix");
INSERT INTO ingredients (id, name) VALUES (265, "Southern Comfort");
INSERT INTO ingredients (id, name) VALUES (266, "Soy Sauce");
INSERT INTO ingredients (id, name) VALUES (267, "Spiced Rum");
INSERT INTO ingredients (id, name) VALUES (268, "Sprite");
INSERT INTO ingredients (id, name) VALUES (269, "St. Germain");
INSERT INTO ingredients (id, name) VALUES (270, "Strawberries");
INSERT INTO ingredients (id, name) VALUES (271, "Strawberry Liqueur");
INSERT INTO ingredients (id, name) VALUES (272, "Strawberry Schnapps");
INSERT INTO ingredients (id, name) VALUES (273, "Sugar");
INSERT INTO ingredients (id, name) VALUES (274, "Sugar Syrup");
INSERT INTO ingredients (id, name) VALUES (275, "Surge");
INSERT INTO ingredients (id, name) VALUES (276, "Sweet And Sour");
INSERT INTO ingredients (id, name) VALUES (277, "Sweet Vermouth");
INSERT INTO ingredients (id, name) VALUES (278, "Tabasco Sauce");
INSERT INTO ingredients (id, name) VALUES (279, "Tea");
INSERT INTO ingredients (id, name) VALUES (280, "Tennessee Whiskey");
INSERT INTO ingredients (id, name) VALUES (281, "Tequila");
INSERT INTO ingredients (id, name) VALUES (282, "Thyme");
INSERT INTO ingredients (id, name) VALUES (283, "Tia Maria");
INSERT INTO ingredients (id, name) VALUES (284, "Tomato Juice");
INSERT INTO ingredients (id, name) VALUES (285, "Tonic Water");
INSERT INTO ingredients (id, name) VALUES (286, "Triple Sec");
INSERT INTO ingredients (id, name) VALUES (287, "Tropicana");
INSERT INTO ingredients (id, name) VALUES (288, "Vanilla");
INSERT INTO ingredients (id, name) VALUES (289, "Vanilla Extract");
INSERT INTO ingredients (id, name) VALUES (290, "Vanilla Ice-Cream");
INSERT INTO ingredients (id, name) VALUES (291, "Vanilla Syrup");
INSERT INTO ingredients (id, name) VALUES (292, "Vanilla Vodka");
INSERT INTO ingredients (id, name) VALUES (293, "Vermouth");
INSERT INTO ingredients (id, name) VALUES (294, "Vodka");
INSERT INTO ingredients (id, name) VALUES (295, "Water");
INSERT INTO ingredients (id, name) VALUES (296, "Whipped Cream");
INSERT INTO ingredients (id, name) VALUES (297, "Whipping Cream");
INSERT INTO ingredients (id, name) VALUES (298, "Whiskey");
INSERT INTO ingredients (id, name) VALUES (299, "White Creme De Menthe");
INSERT INTO ingredients (id, name) VALUES (300, "White Rum");
INSERT INTO ingredients (id, name) VALUES (301, "White Wine");
INSERT INTO ingredients (id, name) VALUES (302, "Wild Turkey");
INSERT INTO ingredients (id, name) VALUES (303, "Wine");
INSERT INTO ingredients (id, name) VALUES (304, "Worcestershire Sauce");
INSERT INTO ingredients (id, name) VALUES (305, "Wormwood");
INSERT INTO ingredients (id, name) VALUES (306, "Yellow Chartreuse");
INSERT INTO ingredients (id, name) VALUES (307, "Yukon Jack");
INSERT INTO ingredients (id, name) VALUES (308, "Zima");
