-- 1. exported mapping of ingredient name to snack name from sheets
-- 2. asked chatgpt to build update query from the mapping: https://chatgpt.com/share/68402f1a-0708-800e-aafd-b6cf01facba8
-- 3. wrapped every column in lower() and trim() to remove leading/trailing spaces and convert all characters to lower case. Because we have inconsistent values in different sheets.
WITH alcohol_snack(alcohol, snack_name) AS (VALUES ('Vodka', 'Smoked Salmon Crackers'),
                                                   ('Lemon Vodka', 'Smoked Salmon Crackers'),
                                                   ('Peach Vodka', 'Smoked Salmon Crackers'),
                                                   ('Raspberry Vodka', 'Smoked Salmon Crackers'),
                                                   ('Vanilla Vodka', 'Smoked Salmon Crackers'),
                                                   ('Absolut Vodka', 'Smoked Salmon Crackers'),
                                                   ('Absolut Peppar', 'Smoked Salmon Crackers'),
                                                   ('Absolut Citron', 'Smoked Salmon Crackers'),
                                                   ('Absolut Kurant', 'Smoked Salmon Crackers'),
                                                   ('Gin', 'Salt and Vinegar Chips'),
                                                   ('Whisky', 'Dark Chocolate (with Chili or Orange) '),
                                                   ('Whiskey', 'Dark Chocolate (with Chili or Orange) '),
                                                   ('Crown Royal', 'Dark Chocolate (with Chili or Orange) '),
                                                   ('Jack Daniels', 'Dark Chocolate (with Chili or Orange) '),
                                                   ('Tennessee whiskey', 'Dark Chocolate (with Chili or Orange) '),
                                                   ('Scotch', 'Dark Chocolate (with Chili or Orange) '),
                                                   ('Blended Scotch', 'Dark Chocolate (with Chili or Orange) '),
                                                   ('Johnnie Walker', 'Dark Chocolate (with Chili or Orange) '),
                                                   ('Islay single malt Scotch',
                                                    'Dark Chocolate (with Chili or Orange) '),
                                                   ('Blended whiskey', 'Dark Chocolate (with Chili or Orange) '),
                                                   ('Irish whiskey', 'Dark Chocolate (with Chili or Orange) '),
                                                   ('Rum', 'Dried Fruits (Pineapple, Apricot)'),
                                                   ('Light rum', 'Dried Fruits (Pineapple, Apricot)'),
                                                   ('Dark rum', 'Dried Fruits (Pineapple, Apricot)'),
                                                   ('White Rum', 'Coconut chips'),
                                                   ('Malibu Rum', 'Coconut chips'),
                                                   ('Gold rum', 'Dried Fruits (Mango, Strawberry)'),
                                                   ('Spiced rum', 'Dried Fruits (Mango, Strawberry)'),
                                                   ('Coconut rum', 'Coconut chips'),
                                                   ('Malibu rum', 'Coconut chips'),
                                                   ('blackstrap rum', 'Coconut chips'),
                                                   ('Añejo rum', 'Dried Fruits (Mango, Strawberry)'),
                                                   ('Tequila', 'Tortilla Chips with Guacamole '),
                                                   ('Maraschino Liqueur', 'Fruit Skewers'),
                                                   ('Benedictine', 'Salt sticks or pretzels'),
                                                   ('Cognac', 'Matured hard cheese with walnuts'),
                                                   ('Rye Whiskey', 'Smoked Beef Jerky'),
                                                   ('Champagne', 'Macarons'),
                                                   ('Amaretto', 'Amarettini (almond cookies)'),
                                                   ('Rose', 'Antipasti skewers'),
                                                   ('Kahlua', 'Chocolate Chip Cookies'),
                                                   ('Everclear', 'Cheese crackers'),
                                                   ('Brandy', 'Olive Tapenade Toast'),
                                                   ('Blackberry brandy', 'Olive Tapenade Toast'),
                                                   ('Apple brandy', 'Olive Tapenade Toast'),
                                                   ('Cherry brandy', 'Olive Tapenade Toast'),
                                                   ('Peach brandy', 'Olive Tapenade Toast'),
                                                   ('Triple sec', 'Roasted almonds'),
                                                   ('Beer', 'Paprika Chips'),
                                                   ('Guinness stout', 'Paprika Chips'),
                                                   ('Corona', 'Paprika Chips'),
                                                   ('Ginger beer', 'Paprika Chips'),
                                                   ('Lager', 'Paprika Chips'),
                                                   ('Black Sambuca', 'Goat Cheese Appetizer'),
                                                   ('Ricard', 'Goat Cheese Appetizer'),
                                                   ('Sambuca', 'Goat Cheese Appetizer'),
                                                   ('Ouzo', 'Goat Cheese Appetizer'),
                                                   ('Red wine', ' Baked Camembert'),
                                                   ('White Wine', 'Grapes and mild soft cheese'),
                                                   ('Sherry', 'Grapes and mild soft cheese'),
                                                   ('Wine', 'Grapes and mild soft cheese'),
                                                   ('Port', 'Grapes and mild soft cheese'),
                                                   ('Ruby Port', 'Grapes and mild soft cheese'),
                                                   ('Wild Turkey', 'Caramel popcorn'),
                                                   ('Bourbon ', 'Caramel popcorn'),
                                                   ('Jim Beam', 'Caramel popcorn'),
                                                   ('Coffee Liqueur', 'Dark Chocolate'),
                                                   ('Vermouth', 'Garlic & Herb Baguette'),
                                                   ('Sweet Vermouth', 'Chocolate Candy'),
                                                   ('Dry Vermouth', 'Garlic & Herb Baguette'),
                                                   ('Rosso Vermouth', 'Garlic & Herb Baguette'),
                                                   ('Blackberry brandy', 'Olive Tapenade Toast'),
                                                   ('Aperol', 'Green or black olives (stuffed or marinated)'),
                                                   ('Prosecco', 'Grapes and mild soft cheese'),
                                                   ('Campari', 'Green or black olives (stuffed or marinated)'),
                                                   ('Apricot brandy', 'Olive Tapenade Toast'),
                                                   ('Southern Comfort', 'Salted Chips'),
                                                   ('Sloe gin', 'Salted Chips'),
                                                   ('Yellow Chartreuse', 'Salted Chips'),
                                                   ('Green Chartreuse', 'Salted Chips'),
                                                   ('Kummel', 'Fruit Skewers'),
                                                   ('White Creme de Menthe', 'Salted Chips'),
                                                   ('Applejack', 'Cashews and Dried Cranberries'),
                                                   ('Green Creme de Menthe', 'Salted Chips'),
                                                   ('Grand Marnier', 'Roasted almonds'),
                                                   ('Butterscotch schnapps', 'Fruit Skewers'),
                                                   ('Orange Curacao', 'Roasted almonds'),
                                                   ('Blue Curacao', 'Roasted almonds'),
                                                   ('Curacao', 'Roasted almonds'),
                                                   ('Tia maria', 'Salted Chips'),
                                                   ('Cachaca', 'Salted Chips'),
                                                   ('Dubonnet Rouge', 'Salted Chips'),
                                                   ('Galliano', 'Salted Chips'),
                                                   ('Strawberry schnapps', 'Fruit Skewers'),
                                                   ('Peach schnapps', 'Fruit Skewers'),
                                                   ('Cherry liqueur', 'Fruit Skewers'),
                                                   ('Baileys irish cream', 'Fruit Skewers'),
                                                   ('Grain alcohol', 'Salted Chips'),
                                                   ('Goldschlager', 'Fruit Skewers'),
                                                   ('Cider', 'Cashews and Dried Cranberries'),
                                                   ('Apple cider', 'Cashews and Dried Cranberries'),
                                                   ('Frangelico', 'Fruit Skewers'),
                                                   ('Cointreau', 'Fruit Skewers'),
                                                   ('Midori melon liqueur', 'Fruit Skewers'),
                                                   ('Pisco', 'Fruit Skewers'),
                                                   ('Chocolate liqueur', 'Fruit Skewers'),
                                                   ('Jägermeister', 'Salt sticks or pretzels'),
                                                   ('Rumple Minze', 'Salt sticks or pretzels'),
                                                   ('Erin Cream', 'Fruit Skewers'),
                                                   ('Advocaat', 'Salted Chips'),
                                                   ('Apple schnapps', 'Fruit Skewers'),
                                                   ('Peppermint schnapps', 'Salt sticks or pretzels'),
                                                   ('Coconut liqueur', 'Fruit Skewers'),
                                                   ('Chambord raspberry liqueur', 'Fruit Skewers'),
                                                   ('Godiva liqueur', 'Dark Chocolate'),
                                                   ('Pisang Ambon', 'Salted Chips'),
                                                   ('Cherry Heering', 'Salted Chips'),
                                                   ('Creme de Banane', 'Salted Chips'),
                                                   ('Kiwi liqueur', 'Fruit Skewers'),
                                                   ('Peachtree schnapps', 'Fruit Skewers'),
                                                   ('Surge', 'Salted Chips'),
                                                   ('Raspberry liqueur', 'Fruit Skewers'),
                                                   ('Bacardi Limon', 'Salted Chips'),
                                                   ('Aquavit', 'Salted Chips'),
                                                   ('Strawberry liqueur', 'Fruit Skewers'),
                                                   ('Zima', 'Salted Chips'),
                                                   ('Absinthe', 'Salted Chips'),
                                                   ('Bacardi', 'Salted Chips'),
                                                   ('Maui', 'Salted Chips'),
                                                   ('St. Germain', 'Salted Chips'),
                                                   ('Creme de Mure', 'Fruit Skewers'),
                                                   ('Creme de Cassis', 'Fruit Skewers'),
                                                   ('Lillet Blanc', 'Green or black olives (stuffed or marinated)'),
                                                   ('Lillet', 'Green or black olives (stuffed or marinated)'),
                                                   ('Mezcal', 'Salted Chips'),
                                                   ('Passoa', 'Salted Chips'),
                                                   ('Falernum', 'Salted Chips'),
                                                   ('Hpnotiq', 'Salted Chips'),
                                                   ('Passoa', 'Fruit Skewers'),
                                                   ('Amaro Montenegro', 'Salted Chips'),
                                                   ('Yukon Jack', 'Salted Chips'))
UPDATE ingredients
SET id_snack = (SELECT snacks.id
                FROM snacks
                         JOIN alcohol_snack ON lower(trim(snacks.name)) = lower(trim(alcohol_snack.snack_name))
                WHERE lower(trim(ingredients.name)) = lower(trim(alcohol_snack.alcohol)))
WHERE id_snack IS NULL
  AND EXISTS (SELECT 1
              FROM alcohol_snack
              WHERE lower(trim(ingredients.name)) = lower(trim(alcohol_snack.alcohol)));
